title: Gautam Bastian
description: Economist. Researcher. Writer.
author:
  name: Gautam Bastian
  linkedin: https://www.linkedin.com/in/gautambastian
  scholar: https://scholar.google.com/citations?user=vMkDMmwAAAAJ&hl=en

baseurl: ""
url: "https://gautambastian.com"

# Build settings
markdown: kramdown
permalink: /blog/:year/:month/:day/:title/

# Exclude from build
exclude:
  - _obsidian/
  - Gemfile
  - Gemfile.lock
  - README.md
